postgres:
  dsn: "host=localhost port=5432 user=vidanalytics password=secret dbname=runner sslmode=disable"

minio:
  endpoint: "localhost:9000"
  access_key: "minio-access-key"
  secret_key: "minio-secret-key"

kafka:
  brokers:
    - "localhost:9091"
  group_id: "video-runner-group"
  scenario_topic: "video-scenarios"
  heartbeat_topic: "heartbeats"

detection:
  endpoint: "http://localhost:8004"
